/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author MICAELA
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrom
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelMenu = new javax.swing.JPanel();
        labelBienvenidos = new javax.swing.JLabel();
        labelOpcion = new javax.swing.JLabel();
        botonProductos = new javax.swing.JButton();
        botonClientes = new javax.swing.JButton();
        botonVentas = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(204, 204, 255));

        labelBienvenidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelBienvenidos.setForeground(new java.awt.Color(0, 0, 0));
        labelBienvenidos.setText("¡Atypical Sport!");

        labelOpcion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelOpcion.setForeground(new java.awt.Color(0, 0, 0));
        labelOpcion.setText("Seleccione una opción:");

        botonProductos.setBackground(new java.awt.Color(255, 255, 255));
        botonProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonProductos.setForeground(new java.awt.Color(0, 0, 0));
        botonProductos.setText("Productos");

        botonClientes.setBackground(new java.awt.Color(255, 255, 255));
        botonClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonClientes.setForeground(new java.awt.Color(0, 0, 0));
        botonClientes.setText("Clientes");

        botonVentas.setBackground(new java.awt.Color(255, 255, 255));
        botonVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonVentas.setForeground(new java.awt.Color(0, 0, 0));
        botonVentas.setText("Ventas");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBienvenidos)
                            .addComponent(labelOpcion))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelBienvenidos)
                .addGap(18, 18, 18)
                .addComponent(labelOpcion)
                .addGap(18, 18, 18)
                .addComponent(botonProductos)
                .addGap(34, 34, 34)
                .addComponent(botonClientes)
                .addGap(29, 29, 29)
                .addComponent(botonVentas)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonClientes;
    public javax.swing.JButton botonProductos;
    public javax.swing.JButton botonVentas;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JLabel labelBienvenidos;
    public javax.swing.JLabel labelOpcion;
    public javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

   public JButton getBotonProductos() {
    return botonProductos;
}

public JButton getBotonClientes() {
    return botonClientes;
}

public JButton getBotonVentas() {
    return botonVentas;
}
}
