/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MICAELA
 */
public class VentasFrame extends javax.swing.JFrame {

     
     
    public VentasFrame() {
        initComponents();
    }
    
    public String getCodigoProducto() {
        return textCodigo.getText();
    }
    
    // Getter para la cantidad
    public String getCantidad() {
        return (String) comboBoxCantidad.getSelectedItem();
    }
    
    // Getter para la fecha de venta
    public String getFechaVenta() {
        return formattedFecha.getText();
    }
    
    // Getter para el modelo de la tabla de ventas
    public DefaultTableModel getVentasTableModel() {
        return (DefaultTableModel) tableVentas.getModel();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        panelVentas = new javax.swing.JPanel();
        labelVentas = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        labelCantidad = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        comboBoxCantidad = new javax.swing.JComboBox<>();
        formattedFecha = new javax.swing.JFormattedTextField();
        buttonModificar = new javax.swing.JButton();
        buttonAgregar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableVentas = new javax.swing.JTable();
        buttonVolver = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelVentas.setBackground(new java.awt.Color(204, 204, 255));

        labelVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelVentas.setForeground(new java.awt.Color(0, 0, 0));
        labelVentas.setText("Ventas:");

        labelCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCodigo.setForeground(new java.awt.Color(0, 0, 0));
        labelCodigo.setText("Código del producto:");

        textCodigo.setBackground(new java.awt.Color(255, 255, 255));

        labelCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCantidad.setForeground(new java.awt.Color(0, 0, 0));
        labelCantidad.setText("Cantidad:");

        labelFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(0, 0, 0));
        labelFecha.setText("Fecha de venta:");

        comboBoxCantidad.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxCantidad.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        comboBoxCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCantidadActionPerformed(evt);
            }
        });

        formattedFecha.setBackground(new java.awt.Color(255, 255, 255));
        formattedFecha.setColumns(3);
        formattedFecha.setForeground(new java.awt.Color(0, 0, 0));
        try {
            formattedFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedFechaActionPerformed(evt);
            }
        });

        buttonModificar.setBackground(new java.awt.Color(204, 204, 204));
        buttonModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonModificar.setForeground(new java.awt.Color(0, 0, 0));
        buttonModificar.setText("Modificar");

        buttonAgregar.setBackground(new java.awt.Color(204, 204, 204));
        buttonAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAgregar.setForeground(new java.awt.Color(0, 0, 0));
        buttonAgregar.setText("Agregar");

        buttonEliminar.setBackground(new java.awt.Color(204, 204, 204));
        buttonEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        buttonEliminar.setText("Eliminar");

        tableVentas.setBackground(new java.awt.Color(255, 255, 255));
        tableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código del producto", "Cantidad", "Fecha de venta"
            }
        ));
        jScrollPane3.setViewportView(tableVentas);

        buttonVolver.setBackground(new java.awt.Color(204, 204, 204));
        buttonVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonVolver.setForeground(new java.awt.Color(0, 0, 0));
        buttonVolver.setText("Volver");

        javax.swing.GroupLayout panelVentasLayout = new javax.swing.GroupLayout(panelVentas);
        panelVentas.setLayout(panelVentasLayout);
        panelVentasLayout.setHorizontalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentasLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(98, Short.MAX_VALUE))
                    .addGroup(panelVentasLayout.createSequentialGroup()
                        .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelVentas)
                            .addGroup(panelVentasLayout.createSequentialGroup()
                                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelVentasLayout.createSequentialGroup()
                                        .addComponent(buttonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelVentasLayout.createSequentialGroup()
                                        .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelCodigo)
                                            .addComponent(labelCantidad)
                                            .addComponent(labelFecha))
                                        .addGap(32, 32, 32)
                                        .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboBoxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(formattedFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(23, 23, 23)
                                .addComponent(buttonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelVentasLayout.setVerticalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelVentas)
                .addGap(28, 28, 28)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(textCodigo))
                .addGap(27, 27, 27)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantidad)
                    .addComponent(comboBoxCantidad))
                .addGap(29, 29, 29)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecha)
                    .addComponent(formattedFecha))
                .addGap(26, 26, 26)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEliminar)
                    .addComponent(buttonVolver))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formattedFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedFechaActionPerformed

    private void comboBoxCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentasFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonAgregar;
    public javax.swing.JButton buttonEliminar;
    public javax.swing.JButton buttonModificar;
    public javax.swing.JButton buttonVolver;
    public javax.swing.JComboBox<String> comboBoxCantidad;
    public javax.swing.JFormattedTextField formattedFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public javax.swing.JLabel labelCantidad;
    public javax.swing.JLabel labelCodigo;
    public javax.swing.JLabel labelFecha;
    public javax.swing.JLabel labelVentas;
    public javax.swing.JPanel panelVentas;
    public javax.swing.JTable tableVentas;
    public javax.swing.JTextField textCodigo;
    // End of variables declaration//GEN-END:variables

    public JButton getButtonAgregar() {
        return buttonAgregar;
    }

    public JButton getButtonEliminar() {
        return buttonEliminar;
    }

    public JButton getButtonModificar() {
        return buttonModificar;
    }


    public JComboBox<String> getComboBoxCantidad() {
        return comboBoxCantidad;
    }

    public JFormattedTextField getFormattedFecha() {
        return formattedFecha;
    }
    
    public JButton getButtonVolver() {
        return buttonVolver;
}
}
